#pragma once

#include <cstdlib>
#include <string>
#include <list>
#include <queue>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <stack>
#include <algorithm>
#include <iostream>
#include <limits>
#include <assert.h>
#include <atomic>
#include <functional>
#include <fstream>
#include <memory>
#include "macros.h"
#include "utils.h"
#include "platform.h"
