#CXX = clang-6.0
#CXX = g++-7.3

PREFIX ?= /usr/local

CXXFLAGS += -fPIC -std=c++17 -O3 -DNDEBUG -I$(CASH_HOME)/include -Wall -Wextra -pedantic
#CXXFLAGS += -fPIC -std=c++17 -O0 -g -I$(CASH_HOME)/include -Wall -Wextra -pedantic

LDFLAGS += -shared -L$(CURDIR)/lib

# Target
TARGET_DIR := lib

PROJECT = libcash

SRCS = ../src/utils.cpp \
       ../src/platform.cpp \
       ../src/system.cpp \
       ../src/lnodeimpl.cpp \
       ../src/ioimpl.cpp \
       ../src/proxyimpl.cpp \
       ../src/cdimpl.cpp \
       ../src/litimpl.cpp \
       ../src/regimpl.cpp \
       ../src/memimpl.cpp \
       ../src/selectimpl.cpp \
       ../src/aluimpl.cpp \
       ../src/bindimpl.cpp \
       ../src/assertimpl.cpp \
       ../src/timeimpl.cpp \
       ../src/printimpl.cpp \
       ../src/udfimpl.cpp \
       ../src/lnode.cpp \
       ../src/logic.cpp \
       ../src/context.cpp \
       ../src/compile.cpp \
       ../src/simref.cpp \
       ../src/simjit.cpp \
       ../src/deviceimpl.cpp \
       ../src/simulatorimpl.cpp \
       ../src/tracerimpl.cpp \
       ../src/verilogwriter.cpp \
       ../src/firrtlwriter.cpp \
       ../src/eda/altera/avalon_sim.cpp

OBJS := $(SRCS:.cpp=.o)

all : $(TARGET_DIR) $(TARGET_DIR)/$(PROJECT).so

$(TARGET_DIR) :
	mkdir $(TARGET_DIR)

$(TARGET_DIR)/$(PROJECT).so : $(OBJS)
	$(CXX) $^ $(LDFLAGS) -o $@

%.o :   %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

.depend: $(SRCS)
	$(CXX) $(CXXFLAGS) -MM $^ > .depend;

clean:
	rm -rf $(PROJECT).so $(OBJS) lib *.gcda *.gcno .depend *~ *\#

ifneq ($(MAKECMDGOALS),clean)
    -include .depend
endif
