#CXX = clang-8.0
#CXX = g++-7.4

CXXFLAGS += -std=c++17 -O3 -DNDEBUG -I$(CASH_HOME)/include -Wall -Wextra -pedantic
#CXXFLAGS += -std=c++17 -O0 -g -I$(CASH_HOME)/include -Wall -Wextra -pedantic
LDFLAGS += -L$(CASH_HOME)/lib -lcash

SRCS = adder.cpp counter.cpp fastmul.cpp matmul.cpp fifo.cpp gcd.cpp vending.cpp sobel.cpp fft.cpp aes.cpp vectoradd.cpp

PROJECTS = $(SRCS:.cpp=.out)
PROJECTS_NAMES = $(SRCS:.cpp=)

all: $(PROJECTS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

%.out: %.o
	$(CXX) $^ $(LDFLAGS) -o $@

.depend: $(SRCS)
	$(CXX) $(CXXFLAGS) -MM $^ > .depend;

clean:
	rm -f *.out *.o *.vcd *.iv *.fir .depend *~ *\#

run: $(PROJECTS)
	$(foreach proj, $(PROJECTS), ./$(proj) || exit;)
	$(foreach proj, $(PROJECTS_NAMES), iverilog $(proj)_tb.v -o $(proj)_tb.iv || exit;)
	$(foreach proj, $(PROJECTS_NAMES), vvp $(proj)_tb.iv || exit;)

ifneq ($(MAKECMDGOALS),clean)
    -include .depend
endif
