#pragma once

#include <string.h>
#include <string_view>
#include <list>
#include <queue>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <stack>
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <limits>
#include <assert.h>
#include <atomic>
#include <functional>
#include <variant>
#include <fstream>
#include <sstream>
#include <memory>
#include <typeindex>
#include <type_traits>
#include <stdexcept>
#include "macros.h"
#include "utils.h"
